### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by zeykafx** [RauliL/oddcast-tts-demo#2]
Hello, It would be very useful but how do I use it?

**Comment by RauliL** [comment]
Hello,

Sorry about the lack of documentation. I originally created this for personal use and decided to publish it on GitHub and NPM in case someone else would find use for it. There is a basic usage example in the README.md which shows how to generate URLs to the oddcast.com text-to-speech demo for a specific text and voice. There is no playback or anything included in this library, only URL generation, meaning that you need to implement the actual downloading and playback of the MP3-files yourself.

I created a [wiki page containing all the voices supported by this library](https://github.com/RauliL/oddcast-tts-demo/wiki/List-of-voices) which could be useful before I come up with more detailed documentation on the usage.

**Comment by zeykafx** [comment]
Hello, thanks for the answer.
So I suppose I need to use it inside of Linux right ? It is fine that it is
just url creation, I need it to use in a video project :)

**Comment by RauliL** [comment]
Any OS will do but this requires to be used with Node.js due to it's requirement on the [md5](https://www.npmjs.com/package/md5) library that does not work with browsers for example. Might replace the dependency with something more portable in the future.
